#This Dockerfile builds Apache JMeter Master Executable based on ajeetraina/apache-jmeter-base
FROM sergioubedaportugues/jmeter-base 
LABEL Description="This image is used to start the Apache JMeter Master Executable" Vendor="Collabnix" Version="1.0"
#Port 60000 required for JMeter Master
EXPOSE 60000